name: GitHub Metrics
on:
  schedule:
    - cron: "30 18 * * *" # Runs at 18:30 UTC (12:00 AM IST)
    - cron: "30 6 * * *" # Runs at 06:30 UTC (12:00 PM IST)
    - cron: "30 12 * * *" # Runs at 12:30 UTC (6:00 PM IST)
  workflow_dispatch: # Or manually trigger it
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: Leo-Stephen
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Kolkata
          # config_display: large
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_stars: yes
          plugin_stars_limit: 4
