name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch: # Or manually trigger it
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Leo-Stephen
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_stars: yes
          plugin_stars_limit: 4
